<!DOCTYPE HTML>
<html lang="en">
	<head>
	    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
   		<link href="/css/bootstrap.css" rel="stylesheet">
    	<link href="/css/bootstrap-theme.css" rel="stylesheet">
    	<link href="../css/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="../css/style.css" media="screen" rel="stylesheet" type="text/css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!--script import to allow menutoggle for smallscreens-->
        <script src="/js/bootstrap.min.js"></script>
    	 <title>Baud Games: <?php echo $view->pageTitle; ?></title>
    </head>
    <body>
		<header class="col-xs-6 col-xs-offset-3">
            <img src="images/Facebook-Banner.jpg"
            width="100%"
            >
        </header>
