<div class="col-xs-10 col-xs-offset-1">
	<div class="col-md-4 col-md-offset-3 col-xs-8 col-xs-offset-2">
		<section class="options">
			<p>Want to play Blackjack?</p>
			<form action="games/Blackjack/game.php"
			method="post"
				<p> Email: <input type="text" name="email"/></p>
				<p><input type="submit" name="play" value="PLAY!"/></p>           
			</form>
		</section>        
		<section class="options">
			<p>Login to BaudGames server</p>
			<form action="user.php" method="post">
				<p> Email: <input type="text" name="email"/></p>
	 			<p> Password: <input type="text" name="password"/></p> 
	 			<p><input type="submit" name="login" value="Log In"/></p>
			</form>
		</section>     
		<section class="options">
			<p>Create New Account</p>
			<form action="user.php" method="post">
				<p> Name: <input type="text" name="name"/></p>
				<p> Email: <input type="text" name="email"/></p>
				<p> Password: <input type="text" name="password"/></p> 
				<p><input type="submit" name="create" value="Create Account"/></p>
			</form>  
		</section>
	</div>
</div>

