<script>
	$(document).ready(function(){
    	$("#hit").click(function(){
			$("div").animate({left: '250px'});
		});
    	$("#stick").click(function(){
        	$("p").append("HTML: ");
    	});
});
</script>
    <main>
        <h2>Your Move!</h2>

        <div>
	<p>test</p></div>

        <form action="game.php" method="post">
            <p><input type="submit" id="hit" name="hit" value="Hit Me!"/></p>
        </form>

        <form action="game.php" method="post">
            <p><input type="submit" id="stick" name="stick" value="Stick!"/></p>
        </form>
    </main>
    